# 追加した規約ファイル読込
require:
  - rubocop-rails

# ダブルクォーテーション除外
Style/StringLiterals:
  Enabled: false

AllCops:
  # NewCops: enableを追加することで、RuboCopのバージョンがあがった際に追加されたCopを自動で有効にできます
  NewCops: enable

  # Rubyバージョン指定
  TargetRubyVersion: 3.1.0

  # 除外したい場所
  # インデントいじるとエラーになる
  Exclude:
    # TODO: 後ほど解放
    - "spec/**/*"
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false
